### ISSUE TITLE
Compilation on OSX 10.9 fails

### ISSUE THREAD

**Issue by rubenfonseca** [kulp/tenyr#26]
Hi! When compiling on OSX 10.9 the build fails with a strange error:

```
./src/gen/debugger_parser.c:1535:41: error: use of undeclared identifier 'yyscanner'
      yychar = yylex (&yylval, &yylloc, yyscanner);
```

To fix it I had to add `void *yyscanner;` to both `debugger_parser.y` and `parser.y`. Did you ever experienced this?

**Comment by kulp** [comment]
I reproduced an issue that looks like this on a codeanywhere instance with flex 2.5.35 and bison 3.0.2. Now I might be able to debug it.
